### ISSUE TITLE
Error on play

### ISSUE THREAD

**Issue by Darth-Carrotpie** [zombience/audio_analyzer#6]
Current version spits two errors on play:
Cannot Initialize property additionalIl2CppArgs::additionalIl2CppArgs. Properties serialization is locked-down.
UnityEditor.Modules.ModuleManager:InitializePlatformSupportModules()
and
Cannot Initialize property Android::ScriptingBackend. Properties serialization is locked-down.
UnityEditor.Modules.ModuleManager:InitializePlatformSupportModules()
Also: OnGui script for audio device selection still wont work.

**Comment by Darth-Carrotpie** [comment]
P.S. My unity version is 5.4.1f1

**Comment by zombience** [comment]
This package is completely untested on Android. I can look into making that
work, but I probably won't have time to really dive into the issue any time
soon. I will leave this issue open for the future when I do.

Can you describe the process by which you arrived at the select input bug?
Is that happening on Android or in editor?

Jason Araujo

---

Not sure why it's important to note that this was sent from a phone... But
it was.

**Comment by Darth-Carrotpie** [comment]
All of this is on editor. Not doing anything with android currently, just windows.
bug: add gui script to any object > play > click any button > error.
I've told this before....

**Comment by zombience** [comment]
RE: GUI bug
do  NOT add the gui script manually. it is not intended to be used that way, which is what i wrote in the previous issue thread. 
i have updated the script to prevent that from happening. pull the latest commit. 
once the scene is running, press key "I" (that's I for Input), and the selector gui will automatically be added and then be disposed when it is no longer needed. 

RE: IL2CPP errors in your log: "Cannot Initialize property Android::ScriptingBackend"
when you go to File > Build Settings in Unity, in the window, which platform do you have selected? There should be zero errors referencing Android if you're building to PC / OSX.

**Comment by zombience** [comment]
are you still having this issue? let me know so i can either offer help or close this issue. 
cheers

**Comment by Darth-Carrotpie** [comment]
Ok. Had no clue about pressing "I" key... Haven't worked with legacy GUI stuff myself. Anyways, I'll check the code and try to discern how to port it to canvas and proper buttons myself, thanks for clearing things up.
You are right about these android errors. My platform was selected as android, which will be the final target platform. It's mainly why I'm doing this anyways, windows being only the "work in progress" platform, to test things up and faster workflow. I see that it's not laying out properly now, but if you got no time to look into it, perhaps I might find smth out myself.
Thanks again :)

**Comment by zombience** [comment]
closing this issue since build platform was the problem. 
will update to canvas type gui in the future, that's pretty easy.

**Comment by Darth-Carrotpie** [comment]
Ok. So tried some stuff around, apparently on android this doesn't work entirely. No errors nothing, just mic keeps silent... which is sad, cause I really liked the approach.

**Comment by zombience** [comment]
understood. as i've said above and is also now noted in the documentation (which you can see on the main page), this was neither developed for nor tested on android. so if it worked on android, that would be a happy accident. 

another user had said that it worked for them on android, except that they had an audio gap in playback (which is a known issue). you may check the open issue and contact the user who made it, and perhaps they can help you get it working.

**Comment by Darth-Carrotpie** [comment]
So. There has been a developement. Apparently it works on others phones by default. My phone is "special". It's a lil broken in every way, so it's the phone's fault (Xiami) fault.

**Comment by zombience** [comment]
Hey there, I've worked on a lot of new improvements and have created a new "beta" branch. 

If you are still interested in the project, I'd really appreciate some testing and feedback. There are some pretty great improvements all across the board: updated inspectors, updated math, and a few extra fx. 

Thanks for your interest, and I hope you get some good use out of it. Let me know if you have any feedback!

Again, that's the "beta" branch
