### ISSUE TITLE
"listen" attribute public

### ISSUE THREAD

**Issue by samavan** [zombience/audio_analyzer#7]
Awesome project and super useful!

Wondering if there is a way to enable/disable the input "Listen" attribute in runtime?
It seems to be protected...

Using the project as submodule then do not want to mess-up...
If by chance there is another way to access it, I'll be glad to know about it!

Thank you so much! :)

**Comment by zombience** [comment]
Hey there, 
you could simply make the "listen" field public and then access it however you like. 
I generally err on the side of keeping things protected/private unless they are needed external to the script for something specific. 

Simply changing it from protected to public will allow you to access the variable as you need. 
Hope that helps.

**Comment by samavan** [comment]
Hi!

Yes did, but locally...
Using as Submodule on 2 machine to remain up to date if by change an update comes up! ^_^...
Can I push it?
Didn't do any change, only switch from private to public...

**Comment by zombience** [comment]
Hi there, sorry I haven't gotten back to you on this. 
I would prefer to keep the main repo using "Listen" as private/protected. 

Also I'm spending a bit of time updating this project, so I'm hoping to have the entirely new and updated repo soon. 

Closing this issue.

**Comment by samavan** [comment]
Thank you!
Didn't have the time recently to work on my Music project also then...
Should be fine soon I guess...
I keep following the feeds from your page! :)

**Comment by zombience** [comment]
Hey there, thanks for continuing to check in on the project. 
I've created a "Beta" branch if you're interested to check it out and give feedback. 
I'll be working in the "dev" branch, so beta will be stable for now. I will be working with a friend to create some really interesting visual fx to improve the examples in the project. 

Go ahead and play around with it! The new version is just about ready, and I could definitely use help testing it out and getting feedback.  Cheers!
